# 项目信息
site_name: LambShaun的个人网站          # 网站标题，会显示在导航栏
site_url: https://lambshaun.github.io/ 
site_author: 陈峰     
site_description: 陈峰个人网站


# 仓库信息 (可选，会在主题中显示仓库链接)
repo_url: https://github.com/LambShaun/lambshaun.github.io/ # 指向你的GitHub仓库
repo_name: lambshaun.github.io

# 编辑URI (可选，方便直接跳转到GitHub编辑页面)
edit_uri: edit/main/docs/   # 如果你的默认分支是 main，并且文档在 docs 目录下

# 导航 (定义网站的导航结构)
nav:
  - 我: 
    - ME/about.md
    - ME/introduction.md
    - ME/profile.md
    - ME/contact.md
    - ME/description.md

  - 博客:
    - BLOG/index.md

  - 开发:
    - DEV/index.md
    - DEV/ESP32AccessKeyBoardDesign.md
    - 编程:
      - C:
        - DEV/Programming/C/review.md

  - 研究:
    - RESEARCH/index.md
    - 软件:
      - Keypirinha:
        - RESEARCH/Apps/Keypirinha.md
    
  - 随笔:
    - ESSAY/index.md
    - ESSAY/202504.md

  - 转载:
    - REPRINT/index.md

  - 网站:
    - WEBSITE/index.md
    


# UI
theme:
  name: material
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | LambShaun  
      icon: fontawesome/brands/github
      link: https://github.com/LambShaun
    - name: Bilibili | LambShaun_
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/474336880
  
    - name: 打赏支持
      icon: fontawesome/solid/mug-saucer
      link: 


# 插件 (可选，例如用于部署的 gh-deploy)
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true